# Generated by Django 6.0.6 on 2026-06-22 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('bags', 'Bags'), ('keys', 'Keys'), ('accessories', 'Accessories'), ('books', 'Books'), ('clothing', 'Clothing'), ('other', 'Other')], default='other', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('date_reported', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('claimed', 'Claimed'), ('returned', 'Returned')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
